### PR TITLE
update kubernetes version from 1.14 to 1.18

### PR DESCRIPTION
**Pull request by diranetafen**
Hi
I've updated PWK to make enable the user to play with the major version.
I remove some not supported options based on kubernetes official documentation

### CODE REVIEW

**Comment by marcosnils** [comment]
Nice @diranetafen!

Have you tried this locally? Does it work?

**Comment by diranetafen** [comment]
Hi
It's work perfectly
I'm using it on my own PWD 
image

**Comment by diranetafen** [comment]
you can see that the master is up and the version is 1.18.0

I will do another PR after this to install automatically the auto-completion

**Comment by marcosnils** [comment]
Nice.. In your image I see that CNI hasn't been initialized. Does CNI
installing works?

**Comment by diranetafen** [comment]
yes 
Weanet is working correctly using the command listed in motd

image

**Comment by diranetafen** [comment]
In the previous capture, the CNI was not ready yet hihi
So all is ok now after CNI up

**Comment by marcosnils** [comment]
Awesome!

I'll update the official environment tonight! I was looking forward to do
this but I haven't had the time. Much appreciated @diranetafen

**Comment by diranetafen** [comment]
You are welcome @marcosnils , another PR is in preparation. I will submit it after this PR will be merged :-)

**Comment by marcosnils** [comment]
hey @diranetafen I just tried to build your dockerfile and I'm getting the following error:

```
#8 25.20 ---> Package tcp_wrappers-libs.x86_64 0:7.6-77.el7 will be installed
#8 25.26 --> Finished Dependency Resolution
#8 25.26 Error: Package: kubeadm-1.18.0-0.x86_64 (kubernetes)
#8 25.26            Requires: kubernetes-cni >= 0.7.5
#8 25.26            Available: kubernetes-cni-0.3.0.1-0.07a8a2.x86_64 (kubernetes)
#8 25.26                kubernetes-cni = 0.3.0.1-0.07a8a2
#8 25.26            Available: kubernetes-cni-0.5.1-0.x86_64 (kubernetes)
#8 25.26                kubernetes-cni = 0.5.1-0
#8 25.26            Available: kubernetes-cni-0.5.1-1.x86_64 (kubernetes)
#8 25.26                kubernetes-cni = 0.5.1-1
#8 25.26            Available: kubernetes-cni-0.6.0-0.x86_64 (kubernetes)
#8 25.26                kubernetes-cni = 0.6.0-0
#8 25.26            Available: kubernetes-cni-0.7.5-0.x86_64 (kubernetes)
#8 25.26                kubernetes-cni = 0.7.5-0
#8 25.26 Error: Package: kubelet-1.18.0-0.x86_64 (kubernetes)
#8 25.26            Requires: kubernetes-cni >= 0.7.5
#8 25.26            Available: kubernetes-cni-0.3.0.1-0.07a8a2.x86_64 (kubernetes)
#8 25.26                kubernetes-cni = 0.3.0.1-0.07a8a2
#8 25.26            Available: kubernetes-cni-0.5.1-0.x86_64 (kubernetes)
#8 25.26                kubernetes-cni = 0.5.1-0
#8 25.26            Available: kubernetes-cni-0.5.1-1.x86_64 (kubernetes)
#8 25.26                kubernetes-cni = 0.5.1-1
#8 25.26            Available: kubernetes-cni-0.6.0-0.x86_64 (kubernetes)
#8 25.26                kubernetes-cni = 0.6.0-0
#8 25.26            Available: kubernetes-cni-0.7.5-0.x86_64 (kubernetes)
#8 25.26                kubernetes-cni = 0.7.5-0
#8 25.26  You could try using --skip-broken to work around the problem
#8 25.31  You could try running: rpm -Va --nofiles --nodigest
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c yum install -y kubectl-1.18.0 kubeadm-1.18.0 kubelet-1.18.0     && yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo     && yum install -y docker-ce git     && sed -i -e '4d;5d;8d' /lib/systemd/system/docker.service     && yum clean all]: runc did not terminate sucessfully
```

Thoughts?

**Comment by diranetafen** [comment]
Hi @marcosnils
I had the same problem, i think there is an issue with centos repo, because after 5 hours the build pass.
I can't explain that because I were using those same lines(yum install kube...) and they always worked

Did you fix it before merging ?

**Pull request merged**
