### PR TITLE
Updating to the latest xterm.js

### PR DESCRIPTION
**Pull request by jtyr**
This PR is updating the `xterm.js` to the latest version. This should replace the PR #304.

### CODE REVIEW

**Comment by marcosnils** [comment]
@jtyr nice. I'll give it a try and hopefully merge.

**Comment by jtyr** [comment]
I have managed to fix the `proposeGeometry` issue but I cannot crack the `toggleFullscreen` function ;o( Any idea haw that should work?

**Comment by marcosnils** [comment]
@jtyr In the very beginning we made some changes to the fit.js and fullscreen.css files because those weren't working for us. Check this commit https://github.com/play-with-docker/play-with-docker/commit/d6c359645c28df9057d5594e67b28f9bf1510eb0#diff-6cc7689c19ae8874b15272921332ad10 specifically to the `fullscreen` CSS class which is the one we customed. 

I wouldn't try to adapt what it is there right now to the upgraded version as it might implicate a lot of changes. What I'd do instead is trying to make the default xterm `fullscreen` plugin work.

**Comment by jtyr** [comment]
I got it working. It was bad property name (`toggleFullscreen` vs `toggleFullScreen`).

**Comment by marcosnils** [comment]
I've just tested it and we almost got it working. For some reason when the screen gets maximized the terminal is not resized correctly. 

Here's a gif that shows what happens:

pwd-screen

**Comment by jtyr** [comment]
It looks like the xterm.js doesn't see the change in the parent element. When I call `proposeGeometry()` in the `toggleFullscreen()` function it still prints the dimension of the non-fullscreen element. I don't know what to do about it.

**Comment by marcosnils** [comment]
Closed by #348

**Pull request closed without merging**
