### PR TITLE
Patching xterm.js to support ALT key

### PR DESCRIPTION
**Pull request by jtyr**
The xterm.js library used by this project doesn't support `ALT` key needed for example for the shortcut `ALT+Backspace` to delete the word before the cursor. This PR is adding this support by backporting the [required change](https://github.com/xtermjs/xterm.js/pull/1180) from the upstream project.

The best would be to update the xterm.js library to the latest version but I guess that might bring some issues. This simple PR avoids all those issues and adds just a feature which will be appreciated by many users.

### CODE REVIEW

**Comment by jtyr** [comment]
The change is kind of difficult to spot. Here is the actual change:

```diff
- if (ev.shiftKey) {\n        result.key = C0.BS; // ^H\n        break;\n      }\n      result.key = C0.DEL;
+ if (ev.shiftKey) {\n        result.key = C0.BS; // ^H\n        break;\n      } else if (ev.altKey) {\n        result.key = C0.ESC + C0.DEL; // \\e ^?\n        break;\n      }\n      result.key = C0.DEL;
```

**Comment by marcosnils** [comment]
Seems like you're only changing the map file?. You need to change the xterm.js as well. The thing is that we're not using a custom version. 

It'd be super nice if we could upgrade PWD to the latest x-term JS version as it offers a lot of benefits ot the current one that we have. Is that something you'll be willing to try out?

**Comment by marcosnils** [comment]
@jtyr any chances to see if PWD can be updated to the latest xterm version?. Would love to move towards that way instead of keep patching our current custom version of the library.

**Comment by marcosnils** [comment]
@jtyr I believe this works now. Can you check?

**Comment by jtyr** [comment]
@marcosnils I wanted to test it but unfortunately I'm not able to create an instance ;o(

**Comment by marcosnils** [comment]
Seems to work for me. Try creating another session.

**Comment by jtyr** [comment]
@marcosnils I have just tried it again on another PC and still cannot create any new instance. I open a new session, see the time count down, but when I click on the "Add new instance" I only see "Creating..." but no instance is created. The "Add new instance" button is displayed again after a short while. My session had ID `bl8lur0t6lug0094qbcg` if you would like to investigate.

**Comment by jtyr** [comment]
@marcosnils The service doesn't seem to work for last few days. I'm getting HTTP ERROR 500.

**Comment by marcosnils** [comment]
When that happens try refreshing the page and pressing the `start` button again.It's working for me now

**Comment by jtyr** [comment]
I have finally managed to create a new instance! Unfortunately the `ALT+Backspace` still doesn't work ;o(

**Comment by marcosnils** [comment]
which site are you testing? play-with-docker? or play-with-kuberentes?

**Comment by jtyr** [comment]
I'm testing it on https://labs.play-with-k8s.com.

**Comment by marcosnils** [comment]
That site hasn't been updated yet. Can you try in https://labs.play-with-docker.com?

**Comment by jtyr** [comment]
I can confirm it works on https://labs.play-with-docker.com.

**Comment by marcosnils** [comment]
Nice. I'll update PWK later today.

**Comment by jtyr** [comment]
PWK also doesn't show Memory and CPU stats. It was broken recently a lot (couldn't login - HTTP error 500, couldn't create instance). Today it works for the first time in weeks.

**Comment by MaxPeal** [comment]
with https://github.com/play-with-docker/play-with-docker/pull/348 it is solved
@jtyr @marcosnils IMHO the PR cann be closed

**Pull request closed without merging**
